### ISSUE TITLE
I can visit a publication overview page after logging in

### ISSUE THREAD

**Issue by netsensei** [ugent-library/biblio-backend#1]
**Epic**

As a user (reviewer, author), I can navigate to a page with an overview of publications after logging in.

**Success criteria**

- [x] A page under Biblio publications > Overview
- [x] I can see a titlebar with the heading "Overview publications"
- [x] I can see a search components which allows me to search through the publications.
- [x] Shows a list of publications which are either assigned to me, or authored by me.
- [x] An individual publication is shown as summary view
- [x] I can filter the list via tabs: "All", "My publications", "Registered by me"
- [x] The list contains 10 publications. If there are more publications, I can see pagination.
- [x] The list is ordered by "newest first", or most recently created publications.

**Related stories**

- [x] #2 
- [ ] #3 

**Additional information**

* Requires integration with the Librecat REST API.
* The Mono mockups show a "select publications" checkboxes, but the UI doesn't feature any bulk actions tied to these checkboxes: so can be ignored for now.
