### ISSUE TITLE
I can see / manage full text documents on the "Full text" tab of the detail page of an existing publication.

### ISSUE THREAD

**Issue by netsensei** [ugent-library/biblio-backend#11]
**Epic**

As a user (author, reviewer,...), I can see the detail page of a publication. This page gives me an overview of the publication metadata, associated file assets, datasets, authors/editors and review status.  This helps me manage the publication in Biblio. I can see the "Full text" tab on this page which gives me an overview of uploaded "full text documents". I can add new full text documents and manage already uploaded full text documents.

An epic is a user story which is too large. It is composed of other user stories that all lead to a single large chunk of functionality.

**Success criteria**

- [x] I arrive at a page with a distinct resource URL for this publication.
- [x] I can go back to the publication overview page clicking the "Publications overview" link.  Any active filters are retained.
- [x] I can see the title of the publication.
- [x] I can see a list of "tabs". Clicking on a tab opens the tab.  I can see a "Full text" tab.
- [x] When I click on the "Full text" tab, I can see a list of uploaded full text documents as well as affordances to add new documents and manage already uploaded documents.

**Related user stories**

- [x] #12 
- [x] #13 
- [x] #14 
- [x] #15
- [x] #16 

**Additional information**

TBD
