### ISSUE TITLE
I can see / manage authors / editors on the "Authors & Editors" tab on the detail page of an existing publication

### ISSUE THREAD

**Issue by netsensei** [ugent-library/biblio-backend#17]
**Epic**

As a user (author, reviewer,...), I can see the detail page of a publication. This page gives me an overview of the publication metadata, associated file assets, datasets, authors/editors and review status.  This helps me manage the publication in Biblio. I can see the ""Authors & Editors"" tab on this page which gives me an overview of associated authors & editors. I can add new authors & editors  and manage already associated authors & editors.

An epic is a user story which is too large. It is composed of other user stories that all lead to a single large chunk of functionality.

**Success criteria**

- [x] I arrive at a page with a distinct resource URL for this publication.
- [x] I can go back to the publication overview page clicking the "Publications overview" link.  Any active filters are retained.
- [x] I can see the title of the publication.
- [x] I can see a list of "tabs". Clicking on a tab opens the tab.  I can see a "Authors & Editors" tab.
- [x] When I click on the "Authors & Editors" tab, I can see a list with already associated authors, and a list with already associated editors, well as affordances to add new items to each list and manage already associated items within each list.

**Related user stories**

- [x] #18 
- [x] #19 
- [x] #20 
- [x] #21 
- [x] #22 
- [x] #23 
- [x] #24 

**Additional information**

=> The "Authors & Editors" tab shows a "search component" consisting of a text form element and a set of facet filters. It's unclear how these should operate / how these related to the "editors" and "authors" lists.
