### ISSUE TITLE
I can add a new publication to the system

### ISSUE THREAD

**Issue by netsensei** [ugent-library/biblio-backend#25]
**epic**

As a user (author / reviewer / ...) I can add a single or multiple publications to the system via an easy wizard. The wizard persists its state meaning that when I close and re-open the window, adding a publication means continuing on from the last point in the wizard. This allows me to add one or multiple publications and keep track as I process all required / requested information in the system.

**Success criteria**

- [x] On the "publication overview" page, I can see a big button "Add publication(s)"
- [x] When I hit the button, the sidebar will change and show a set of steps I need to follow to complete the wizard. I land on the first step of the wizard.
- [x] Each step has a titlebar which shows (a) the title of the step, (b) the step number (e.g. "Step 1") and (c) a call to action / submit button which initiates data validation and processing before proceeding to the next step towards completion of the wizard.
- [ ] #171
- [x] I can add a single publication manually.
- [x] I can add multiple publications by importing them from Web of Science, or via import of a bibtext record.

**Related stories**

- [x] #26 
- [ ] #27

**Additional information**

This wizard operates in a slightly different way then what you'd normally expect from a wizard form.

* The wizard persists its state as a session. Closing the window, logging out and back in again,... doesn't discard the session.
* Clicking "Add publication" when there's an active session going on doesn't discard the session: you are taken to the last step you were on when you closed the UI.
* You can't skip forward or backward through the steps of the wizard. This ensures accidental landing in an inconsistent state.
* Moving from the "import file" step to the "complete description" step will require dummy records to be registered in the system.
* Once dummy publications have been created, publications become discoverable for author authors / reviewers. They can be edited from the "publication overview page".  It's possible that multiple people are editing a record while it's still in an active "add publication" session.
* A publication is only "published to biblio" if the person adding the record completes the entire wizard.

Notes:

* It's unclear what the "Save as draft" and "Publish to biblio" buttons on the last step signify. 
* Users can't cancel the wizard halfway through. You need to finish the entire wizard in order to start a completely new session. It means that you need to finish creating publications first before you can either delete them; or add new publication(s).
* It's unclear from the Mono mockups which validation rules will restrict you from going to the next step (e.g. you need to complete the entire record before you can "publish to biblio") **Risk: of blocking the wizard entirely with a record which can't be completed because a crucial piece of information isn't available.** So, we need to choose our validation rules carefully here.
* Don't implement validation / processing rules in the application => Librecat workflow is leading.
