### ISSUE TITLE
I can add a new dataset to the system

### ISSUE THREAD

**Issue by netsensei** [ugent-library/biblio-backend#31]
**epic**

As a user (author / reviewer / ...) I can add a single dataset to the system via an easy wizard. The wizard persists its state meaning that when I close and re-open the window, adding a dataset means continuing on from the last point in the wizard. This allows me to add a single dataset and keep track as I process all required / requested information in the system.

**Success criteria**

- [x] On the "datast overview" page, I can see a big button "Add dataset"
- [x] When I hit the button, the sidebar will change and show a set of steps I need to follow to complete the wizard. I land on the first step of the wizard.
- [x] Each step has a titlebar which shows (a) the title of the step, (b) the step number (e.g. "Step 1") and (c) a call to action / submit button which initiates data validation and processing before proceeding to the next step towards completion of the wizard.
- [x] I can add a single dataset manually.

**Related stories**

- [ ] #32 

**Additional information**

This wizard operates in a slightly different way then what you'd normally expect from a wizard form.

* The wizard persists its state as a session. Closing the window, logging out and back in again,... doesn't discard the session.
* Clicking "Add dataset" when there's an active session going on doesn't discard the session: you are taken to the last step you were on when you closed the UI.
* You can't skip forward or backward through the steps of the wizard. This ensures accidental landing in an inconsistent state.
* Moving from the "Add reference" step to the "complete description" step will require a dummy record to be registered in the system.
* Once a dummy record has been created, the dataset become discoverable for author authors / reviewers. It can be edited from the "dataset overview page".  It's possible that multiple people are editing a record while it's still in an active "add dataset" session.
* A dataset is only "published to biblio" if the person adding the record completes the entire wizard.

Notes:

* Users can't cancel the wizard halfway through. You need to finish the entire wizard in order to start a completely new session. It means that you need to finish creating publications first before you can either delete them; or add new publication(s).
* It's unclear from the Mono mockups which validation rules will restrict you from going to the next step (e.g. you need to complete the entire record before you can "publish to biblio") **Risk: of blocking the wizard entirely with a record which can't be completed because a crucial piece of information isn't available.** So, we need to choose our validation rules carefully here.
* Don't implement validation / processing rules in the application => Librecat workflow is leading.
