### ISSUE TITLE
As a user, I can find help texts with individual form elements when adding or editing a dataset or publication.

### ISSUE THREAD

**Issue by netsensei** [ugent-library/biblio-backend#346]
**Story**

As a user, I can find clear, concise and helpful documentation with individual form elements when adding or editing a dataset or publication. This guides me into adding / editing information in a correct, consistent and accurate fashion.

**Acceptance criteria**

* Form elements show a help text in an unobtrusive manner. (e.g. below the element)
* Help text may contain links which are clearly marked (color, underline,...)
* Help text may also contain examples which are now placeholders in the form elements.
* Help texts are readable, concise and understandable. Help text should be no longer then 60-90 characters. If longer, then link to a separate page.
* Help texts are a visual fit with other parts of a form element: input boxes, buttons, inline errors, supplemental icons,...

**Tasks**

- [ ]  Determine which form elements on which forms definitely need a help text. Replace tooltips whenever possible.
- [ ] Write & edit proper copy for each form element that requires a help text. Copy (c)(s)hould include links to Research Tips / Onderzoektips. Defer long copy to a separate page / site.
- [ ] Add copy to relevant form elements. Use [Bootstrap 4.6](https://getbootstrap.com/docs/4.6/components/forms/#overview) markup for adding help text.

**Additional information**

This ticket consolidates and supersedes these issues:

* #336 
* #335 
* #298 
* #278 
* #339

**Comment by mietcls** [comment]
The requirement for error text is handled in this design, and is possible with Bootstrap: https://biblio-ugent-prototype-emily-v2.vercel.app/biblio/reviewer/publication-detail/description--empty.html

However, what would this look like with regular help text? @emilyvandewalle do we have an example here with the above requirements?

**Comment by mietcls** [comment]
Okay, you can merge it! So you would first read "what is wrong" and after that "how to do it". Makes sense.

Note to self: we will have to review the copy so that it always makes sense.

**Comment by emilyvandewalle** [comment]
Great, thanks! I've added the HTML example [here](https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-forms.html#component-06-form-error-and-help-text)

**Comment by mietcls** [comment]
As seen in the other stories, this one seems done. If anything needs to be adapted we will create new stories.
