### ISSUE TITLE
Snapstore

### ISSUE THREAD

**Issue by nics** [ugent-library/biblio-backend#360]
- [ ] add missing dataset search sort options
- [ ] add missing publication search sort options
- [ ] add missing dataset search facets
- [ ] add missing publication search facets
- [ ] ensure dataset validation matches librecat validation
- [ ] ensure publication validation matches librecat validation
- [ ] improve and complete dataset search schema and search query builder
- [ ] improve and complete publication search schema and search query builder
- [ ] question: switch to gorilla/schema? (avoid go-playground/form bug)
- [ ] add hooks to integrate citation generation
- [ ] add hooks to set thumbnails links
- [ ] split off handle server (mostly done)
- [ ] librecat publication import script (mostly done)
- [ ] librecat dataset import script
- [ ] biblio frontend glue
- [ ] wrap errors
- [ ] version conflict handling
- [ ] add indexing hooks
- [ ] make older snapshots also searchable (memento)
- [ ] fix repeatable field handling (field values doubling)
- [ ] goroutine based workers
- [ ] restrict some features to some (test) users
- [ ] question: use postgres uuid types (or ulid)?
- [ ] controllers other than dataset_abstracts should also handle etags
- [ ] reduce controller boilerplate

**Comment by netsensei** [comment]
**Improve rendering**

Currently, we render content through [unrolled/render](https://github.com/unrolled/render): Every controller calls methods on a `render` instance passing an anonymous struct with domain objects (publication, user, dataset).

This approach has several limitations:

* Lots of repetition / boilerplate code in the controller actions which creates a risk for making typo's.
* Passing domain objects forces us to write extra processing logic as templating functions which has all kinds of limitations (e.g. loss of strong typing)

A typical case: form error handling.

Currently, validation generates a list of paths (a `map` of `string`) referencing fields in the domain object containing faulty data. This list is then passed to a `FormBuilder`  instance which is then called in the template (e.g. `{{.D.Form.Text (.D.Form.Name "title") (.D.Form.Value .D.Publication.Title) (.D.Form.Cols 9) (.D.Form.Required)}}`)  Note how values from the domain object (`publication`) are passed to those methods (`.D.Form.Value .D.Publication.Title`)

Behind the scenes, the form builder has to implement complex logic in order to de-reference the error path and check whether the form element currently being rendered needs to display an error.  Moreover, error handling also provides extra data which needs to be handled: an error message which needs to be localized.

**Path forward**

A/ Instead of passing domain objects (publication, dataset,...) to the template via an anonymous struct, we want to pass an intermediate struct which serves as an interface to the template containing all the data that needs to be rendered.

e.g. an intermediate struct that has a "form" property which is a struct containing fields with ready-to-render domain values as well as other information such as localized inline errors.

We're already doing something like this by composing and passing an anonymous struct to the render function in controller actions. But this should be treated as a 1st class citizen.

B/ Another improvement is moving away from a list of paths pointing to fields in a complex, nested struct that require extra parsing logic in order to be able to de-reference them in the form builder or, worse, the template during rendering when called in the template.

Instead, validation errors would be interspersed directly in a ready to consume form struct that's going to be pushed to the intermediate struct that's passed on to the template.

C/ We want to re-think how we call our rendering logic. We could move towards a `bind`/`render` pattern as implemented by [chi](https://github.com/go-chi/render)
