### ISSUE TITLE
reorganize templates

### ISSUE THREAD

**Issue by netsensei** [ugent-library/biblio-backend#456]
We need to review the structuring of the `views` directory containing all our templates. It's grown organically and lacks some consistent structuring making it a somewhat confusing.

* The directory is called `views` but at the root level, it does contain partials e.g. `_close_modal.gohtml, `_flash.gohtml`.
* Layouts are in their own `layout` folder at the root level. But partials and views share the same folder, only differentiating them with a underscore.
* There are `pages` directories e.g. `dataset/pages` and `pages` and `publication/pages` => it's unclear what the semantics of those are.
* I can spot at least 3 types of views: modal dialogs (e.g. add_publication.gohtml), tabs (e.g. show_publications.gohtml) and refreshes (e.g. refresh_abstract.go) in dataset and publication directories. But they are all lugged into the `dataset` or `publication` directory; whereas on the root level, there's `form`, `fields` and `displays`.  The organization of the templates is subdivided into sets which are named in a fashion which is too generic, or too specific.

So, the goal would be to establish a handful clear conventions that help organize template code.

In that regard, the renderer doesn't care about the organization / naming of templates, so there's lots of flexibility here. Neither should it enforce particular conventions in a hard way as there will be unavoidable exceptions.

**Todo**

- [ ] Hash out a handful of conventions that create a consistent organization of templates
- [ ] Re-organize the directory
- [ ] Change references in the code to the templates

This shouldn't lead to re-writing the templates themselves.

**Comment by nics** [comment]
refactored
