### ISSUE TITLE
I can see / manage record data from a "description" tab on the detail page of an existing publication

### ISSUE THREAD

**Issue by netsensei** [ugent-library/biblio-backend#5]
**Epic**

As a user (author, reviewer,...), I can see the detail page of a publication. This page gives me an overview of the publication metadata, associated file assets, datasets, authors/editors and review status.  This helps me manage the publication in Biblio. I can see the "Description" tab on this page which gives me an overview of record metadata.

An epic is a user story which is too large. It is composed of other user stories that all lead to a single large chunk of functionality.

**Success criteria**

- [x] I arrive at a page with a distinct resource URL for this publication.
- [x] I can go back to the publication overview page clicking the "Publications overview" link.  Any active filters are retained.
- [x] I can see the title of the publication.
- [x] I can see a list of "tabs". Clicking on a tab opens the tab.  I can see a "Description" tab.
- [x] When I open the "Description" tab, I can see metadata fields grouped in collapsed / collapsible fieldsets.
- [x] In the top right, I can see an icon. Clicking it opens a menu with "actionable" items.
- [x] I can see an "Expand" button. When I click, a collapsed summary of the metadata is shown instead of the title of the publication. This is the same summary as shown on the publication overview page.  The "Expand" button is replaced by a "Collapse" button, which closes the folded out summary and replaces it back tot he publication title.

**Related user stories**

- [x] #6 
- [x] #7 
- [x] #8 
- [x] #9 
- [x] #10 

**Additional information**

=> The list of shown fieldsets / fields is dependent on the publication type.  We need to determine per publication type which fields / fieldsets need to be shown in the "Description" tab.
