### ISSUE TITLE
Filtering epic

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#519]
# Filter epic

Add and adapt filters to work as in the old Biblio.

## Adapt filters
- [x] **Fix this one first!** #483 
  - Make sure filters are always visible even if there are no records in that filter (display 0)
  - Make sure checkboxes in filters are always visible even if there are no records in that option (display 0)
- [x] https://github.com/ugent-library/biblio-backend/issues/484 
Add numbers of records to filters
- [x] https://github.com/ugent-library/biblio-backend/issues/504
Fix filter layout

## Add filters
- [x] Librarians tags
  - https://github.com/ugent-library/biblio-backend/issues/511 (epic)
  - https://github.com/ugent-library/biblio-backend/issues/509 (specific story)
- [x] Biblio status: new, private, public, returned
- [x] https://github.com/ugent-library/biblio-backend/issues/520
Publication status (Accepted, published, unpublished)
- [x] https://github.com/ugent-library/biblio-backend/issues/522
Locked / unlocked

- [x] https://github.com/ugent-library/biblio-backend/issues/523
UGent / non UGent records
- [x] Faculty
- [x] Publication type
- [x] https://github.com/ugent-library/biblio-backend/issues/528
WoS type
- [x] https://github.com/ugent-library/biblio-backend/issues/527
Classification
- [x] https://github.com/ugent-library/biblio-backend/issues/529
Publishing year
- [x] https://github.com/ugent-library/biblio-backend/issues/526
VABB type
- [x] https://github.com/ugent-library/biblio-backend/issues/525
File or link type
- [x] https://github.com/ugent-library/biblio-backend/issues/524
With or without message

- [x] #530
- [x] #531

## Out of scope filters
- Faculty: no faculty assigned
- "Created in Biblio" (will never be implemented)

# Success criteria functionality
- [x] Some filters are visible for librarians only: this is defined in the config of the old back-end
- [x] I can access a specific filter by clicking the dropdown
- [x] I can add a filter by selecting one or more checkboxes
- [x] Filters always remain visible even when the results show 0
- [x] Filter options always remain visible even when the results show 0

## Out of scope
- (only if deselect also works) I can select all options of a specific filter at the same time by clicking "select all"
- I can deselect all options of a specific filter at the same time by clicking "deselect all"
- Simplifying the design to make certain tags more manageable
- Reworking the empty value 

# Implementation

### Adding new filters with a checkbox
![Image](https://user-images.githubusercontent.com/1572885/187862303-2ecbdff8-4961-40ab-baf7-3dacfea7dec8.png)

### Adding new filters with an input field
![Image](https://user-images.githubusercontent.com/1572885/188126684-069a60ed-8152-496c-82a2-10f67f25c1cf.png)

### Removing filters
Select all and deselect all out of scope for this filter
![Image](https://user-images.githubusercontent.com/1572885/187862869-9065c8ee-d6fe-409a-a33b-75a6e4b03638.png)

## Components and prototype

Dropdown with divider:
https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-dropdown.html#component-02-dropdown-divider

Example prototype:
https://biblio-ugent-prototype-emily-v2.vercel.app/biblio/reviewer/publications/overview.html

Checkbox:
https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-inputs.html#component-06-checkbox

Input field with help text:
https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-forms.html#component-04-form-with-help-text

### Add new filters
![Image](https://user-images.githubusercontent.com/1572885/187862484-3ac7d14a-3790-4f97-9f8d-334d9e85d521.png)

### Removing filters
![Image](https://user-images.githubusercontent.com/1572885/187863103-5cb291eb-15a1-40d6-9519-d29993672666.png)

**Comment by mietcls** [comment]
Reviewer or researcher only -> will be defined by the config.

**Comment by nicolasfranck** [comment]
@mietcls what is the desired order between these filters/facets?

**Comment by mietcls** [comment]
@nicolasfranck we can reuse the order of the old Biblio for now, and add the "created since" and "updated since" as last.

**Comment by netsensei** [comment]
@mietcls can this one be closed? All stories in this epic seem to be complete?

**Comment by nics** [comment]
everything implemented ... closing this

**Comment by mietcls** [comment]
Sure, I was still waiting for @nicolasfranck's answer but it seems fine :-)
