### ISSUE TITLE
Locking records epic

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#521]
# Epic about locking
- [x] https://github.com/ugent-library/biblio-backend/issues/565
Lock or unlock record (librarian)
- [x] https://github.com/ugent-library/biblio-backend/issues/564
See if record is locked or unlocked (librarians and researchers) in overview
- [x] https://github.com/ugent-library/biblio-backend/issues/576
See if record is locked or unlocked (librarians and researchers) in detail page
- [x] https://github.com/ugent-library/biblio-backend/issues/574
Make locked records non-editable for researchers and administrative support
- [x] https://github.com/ugent-library/biblio-backend/issues/522
Filter on locked records

**Comment by mietcls** [comment]
@nics @nicolasfranck @netsensei are the stories in this epic okay? Is anything missing? I think I failed to write the comments down.

**Comment by netsensei** [comment]
@mietcls Done. Closing this one.
