### ISSUE TITLE
Researcher to Librarian switch

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#557]
# Story

When I am in Biblio and I have multiple roles, I can switch between them.

For instance, if I have written my own publications, but I am also working with Biblio from a librarian perspective, I can switch between them.

# Success criteria
- [x] When only have the role researcher – I cannot see the switch.
- [x] #633
  - [x] From the researcher perspective, I can...
    - [x] I only see the records I added myself
    - [x] I see a specific set of filters #519 
    - [x] see the "publications" and "datasets" menu items
    - [x] switch to librarian
  - [x] From the librarian perspective, I can...
    - [x] see all records added by anyone
    - [x] I see all filters #519 
    - [x] #517
  When I look at the interface from a Researcher perspective, can see the "publications", "datasets" and "dashboard" menu items
    - [x] switch to researcher

## Out of scope
- [ ] Dealing with profiles that create records for researchers that are not themselves, nor from a librarian perspective.

## Related
Fix width of sidebar and wording in prototype: https://github.com/ugent-library/biblio-backend/issues/556

# Implementation

## Design

Switch from researcher perspective
![Image](https://user-images.githubusercontent.com/1572885/188467146-e40bf8b2-78c0-4847-9152-775e7dcc1f7c.png)
![Image](https://user-images.githubusercontent.com/1572885/188467147-7c368cb4-c99d-4516-91dc-6f48b874a914.png)

Black sidebar for librarians
![Image](https://user-images.githubusercontent.com/1572885/188467217-b752a3f8-765c-4386-936c-61944a8527ed.png)

## Copy
- Librarian
- Researcher

## Code

Dropdown
https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-dropdown.html#component-01-dropdown

Prototype
**TODO: Fix sidebar width to fit the word "Researcher"
TODO: Fix wording in sidebar prototype**

Researcher (user): https://biblio-ugent-prototype-emily-v2.vercel.app/biblio/researcher/publications/overview.html
Librarian: https://biblio-ugent-prototype-emily-v2.vercel.app/biblio/reviewer/publications/overview.html

Code example
```
<div class="c-sidebar c-sidebar--dark-gray">
  <div class="dropdown mx-4 mt-1 mb-5">
      <button class="btn btn-outline-light btn-sm btn-block dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="text-truncate">Librarian</span>
      </button>
      <div class="dropdown-menu" style="">
        <a class="dropdown-item" href="/biblio/researcher/publications/overview.html">Researcher</a>
        <a class="dropdown-item active" href="/biblio/reviewer/publications/overview.html">Librarian</a>
      </div>
  </div>
  <div class="c-sidebar__menu">
    <nav>
      <ul class="c-sidebar-menu">
        <li class="c-sidebar__item c-sidebar__item--active">
          <a href="/biblio/reviewer/publications/overview.html">
            <span class="c-sidebar__icon">
              <i class="if if-article"></I>
            </span>
            <span class="c-sidebar__label">Biblio Publications</span>
          </a>
        </li>
        <li class="c-sidebar__item">
          <a href="#">
            <span class="c-sidebar__icon">
              <i class="if if-database"></I>
            </span>
            <span class="c-sidebar__label">Biblio Datasets</span>
          </a>
        </li>
        <li class="c-sidebar__item">
          <a href="/biblio/reviewer/dashboard.html">
            <span class="c-sidebar__icon">
              <i class="if if-grid"></I>
            </span>
            <span class="c-sidebar__label">Dashboard</span>
          </a>
        </li>
      </ul>
    </nav>
  </div>
  <div class="c-sidebar__bottom">
    <img src="/images/logo-ugent-white.svg" alt="Logo UGent" height="48px" width="auto">
  </div>
</div>
```

**Comment by mietcls** [comment]
We probably need a separate world to be able to improve the world for researchers and reviewers for their different needs

**Comment by mietcls** [comment]
@netsensei @nics @nicolasfranck I suggest we for now keep the switch and think about the different efficiency improvements we can make for different profiles later; it might make things too complicated for the short timespan now. What do you think?

**Comment by nics** [comment]
@mietcls completely agree :-)

**Comment by nics** [comment]
resolved by 7a2925c6a559240a3601214e9461fd0bfd74d37a
