### ISSUE TITLE
Withdrawing epic

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#578]
- [x] https://github.com/ugent-library/biblio-backend/issues/575
As a librarian, I can withdraw a record
  - [x] As a researcher, whenever a record has been withdrawn and is not locked, I can still edit the record
  - [x] As a researcher, whenever a record has been withdrawn, I can republish after completing the record
- [x] #580
- [x] #581
- [x] I can filter on withdrawn records
  - [x] Make naming consistent; name "returned" "withdrawn"

Related, locking: #521

**Comment by mietcls** [comment]
"Publish" -> uitgeven of visible maken naar de wereld? "Submit"?

**Comment by netsensei** [comment]
Done. Report bugs, notes in follow up tickets
