### ISSUE TITLE
Authors, editors or creators epic

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backend#603]
# Epic

- I can add authors and editors to a publication
- I can add creators to a dataset

## Success criteria

[Suggestions, to be discussed]

Adding
- [x] I can search through the UGent database to add affiliated authors, editors or creators
https://github.com/ugent-library/biblio-backend/issues/605
  - [x] [TBD] Before I perform my search, there is a blank state that guides me
  https://github.com/ugent-library/biblio-backend/issues/604
  - [x] Based on the information I can see, I can decide who the correct person is
  https://github.com/ugent-library/biblio-backend/issues/606
  - [x] If I don't find any matches in my results, I get guidance
  https://github.com/ugent-library/biblio-backend/issues/607

Editing
- [x] #611
- [x] I can remove authors, editors or creators
- [x] I can adapt the sequence of authors, editors and creators

## Out of scope

- I can add contributors to a dataset
- I can add a author, editor or contributor that was not affiliated to Ghent University at that time
- I can add affiliations outside of UGent departments
- [Splitting up Credit roles and first / last author](https://github.com/ugent-library/biblio-backend/issues/608)

View the bigger, full-blown design here: https://github.com/ugent-library/biblio-backend/issues/397

# Implementation

For implementation, view separate issues above.

## Components

**Modal**
- Normal modal: https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-modals.html#component-01-modal
- Fullscreen modal: https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-modals.html#component-07-modal-fullscreen
- Blank state: https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/c-blank-slate.html

**Search results**
- List groups: https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-list-group.html
- Cards: https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-cards.html
- Forms: https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-forms.html#component-02-form-grid-layout

**Buttons & Icons**
- Buttons: https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-btn-skins.html
- Icons: https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/aov-icons.html

# Questions
- What is the number of results you will see when searching? What is this based on? Do we need a message for people to refine their search criteria?
- Do we want to make adding an external person part of the

**Comment by mietcls** [comment]
I've adapted the stories based on our conversation today @netsensei @nics 
The biggest changes you'll find here:
https://github.com/ugent-library/biblio-backend/issues/605
https://github.com/ugent-library/biblio-backend/issues/611

I've opted for the simplest version for external authors, based on the visual iterations this seemed the best option (non-editable name in the second screen).

**Summary of our conversation:**

Search
- Search on type
- No buttons

Add
- Select author in list or add external
    - Internal:
        - Edit credit
        - Back to search
    - External author:
        - Edit credit
        _- Editable form to confirm name?_ -> not for now
        - Back
    - Other data
        - Edit credit
        - Back

Edit
- Internal
    - Switch by search
        - Connect other identifier
        - Or make external
    - Edit credit
- External
    - Switch by search
        - Connect other identifier
        - Or make external
    - Edit credit

**Comment by mietcls** [comment]
@nics @netsensei apparently we're waiting for each other Matthias told me – this one is ready to go for me after you both say "go" or give me your recommendations!
